mod scancode_map;
pub use self::scancode_map::{*};

#[derive(Clone, Eq, PartialEq, Debug)]
pub struct Key {
	pub label: &'static str,
	pub scan_code: u16,
}

pub static KEYS: &[Key] = &[
	Key { label: "~ `", scan_code: 0x29 },
	Key { label: "! 1", scan_code: 0x02 },
	Key { label: "@ 2", scan_code: 0x03 },
	Key { label: "# 3", scan_code: 0x04 },
	Key { label: "$ 4", scan_code: 0x05 },
	Key { label: "% 5", scan_code: 0x06 },
	Key { label: "^ 6", scan_code: 0x07 },
	Key { label: "& 7", scan_code: 0x08 },
	Key { label: "* 8", scan_code: 0x09 },
	Key { label: "( 9", scan_code: 0x0A },
	Key { label: ") 0", scan_code: 0x0B },
	Key { label: "_ -", scan_code: 0x0C },
	Key { label: "+ =", scan_code: 0x0D },
	Key { label: "Backspace", scan_code: 0x0E },
	Key { label: "Tab", scan_code: 0x0F },
	Key { label: "Q", scan_code: 0x10 },
	Key { label: "W", scan_code: 0x11 },
	Key { label: "E", scan_code: 0x12 },
	Key { label: "R", scan_code: 0x13 },
	Key { label: "T", scan_code: 0x14 },
	Key { label: "Y", scan_code: 0x15 },
	Key { label: "U", scan_code: 0x16 },
	Key { label: "I", scan_code: 0x17 },
	Key { label: "O", scan_code: 0x18 },
	Key { label: "P", scan_code: 0x19 },
	Key { label: "{ [", scan_code: 0x1A },
	Key { label: "} ]", scan_code: 0x1B },
	Key { label: "| \\", scan_code: 0x2B },
	Key { label: "Caps Lock", scan_code: 0x3A },
	Key { label: "A", scan_code: 0x1E },
	Key { label: "S", scan_code: 0x1F },
	Key { label: "D", scan_code: 0x20 },
	Key { label: "F", scan_code: 0x21 },
	Key { label: "G", scan_code: 0x22 },
	Key { label: "H", scan_code: 0x23 },
	Key { label: "J", scan_code: 0x24 },
	Key { label: "K", scan_code: 0x25 },
	Key { label: "L", scan_code: 0x26 },
	Key { label: ": ;", scan_code: 0x27 },
	Key { label: "\" '", scan_code: 0x28 },
	Key { label: "(in'tl )", scan_code: 0x2B },
	Key { label: "Enter", scan_code: 0x1C },
	Key { label: "L SHIFT", scan_code: 0x2A },
	Key { label: "(in'tl )", scan_code: 0x56 },
	Key { label: "Z", scan_code: 0x2C },
	Key { label: "X", scan_code: 0x2D },
	Key { label: "C", scan_code: 0x2E },
	Key { label: "V", scan_code: 0x2F },
	Key { label: "B", scan_code: 0x30 },
	Key { label: "N", scan_code: 0x31 },
	Key { label: "M", scan_code: 0x32 },
	Key { label: "< ,", scan_code: 0x33 },
	Key { label: "> .", scan_code: 0x34 },
	Key { label: "? /", scan_code: 0x35 },
	Key { label: "(in'tl )", scan_code: 0x73 },
	Key { label: "R SHIFT", scan_code: 0x36 },
	Key { label: "L CTRL", scan_code: 0x1D },
	Key { label: "L ALT", scan_code: 0x38 },
	Key { label: "Space Bar", scan_code: 0x39 },
	Key { label: "R ALT", scan_code: 0xE038 },
	Key { label: "R CTRL", scan_code: 0xE01D },
	Key { label: "Insert", scan_code: 0xE052 },
	Key { label: "Delete", scan_code: 0xE053 },
	Key { label: "L Arrow", scan_code: 0xE04B },
	Key { label: "Home", scan_code: 0xE047 },
	Key { label: "End", scan_code: 0xE04F },
	Key { label: "Up Arrow", scan_code: 0xE048 },
	Key { label: "Dn Arrow", scan_code: 0xE050 },
	Key { label: "Page Up", scan_code: 0xE049 },
	Key { label: "Page Down", scan_code: 0xE051 },
	Key { label: "R Arrow", scan_code: 0xE04D },
	Key { label: "Num Lock", scan_code: 0x45 },
	Key { label: "Num 7", scan_code: 0x47 },
	Key { label: "Num 4", scan_code: 0x4B },
	Key { label: "Num 1", scan_code: 0x4F },
	Key { label: "Num /", scan_code: 0xE035 },
	Key { label: "LS+Num /", scan_code: 0xE0B5 },
	Key { label: "RS+Num /", scan_code: 0xE0B6 },
	Key { label: "Num 8", scan_code: 0x48 },
	Key { label: "Num 5", scan_code: 0x4C },
	Key { label: "Num 2", scan_code: 0x50 },
	Key { label: "Num 0", scan_code: 0x52 },
	Key { label: "Num *", scan_code: 0x37 },
	Key { label: "Num 9", scan_code: 0x49 },
	Key { label: "Num 6", scan_code: 0x4D },
	Key { label: "Num 3", scan_code: 0x51 },
	Key { label: "Num .", scan_code: 0x53 },
	Key { label: "Num -", scan_code: 0x4A },
	Key { label: "Num +", scan_code: 0x4E },
	Key { label: "(in'tl )", scan_code: 0x7E },
	Key { label: "NumEnter", scan_code: 0xE01C },
	Key { label: "Esc", scan_code: 0x01 },
	Key { label: "F1", scan_code: 0x3B },
	Key { label: "F2", scan_code: 0x3C },
	Key { label: "F3", scan_code: 0x3D },
	Key { label: "F4", scan_code: 0x3E },
	Key { label: "F5", scan_code: 0x3F },
	Key { label: "F6", scan_code: 0x40 },
	Key { label: "F7", scan_code: 0x41 },
	Key { label: "F8", scan_code: 0x42 },
	Key { label: "F9", scan_code: 0x43 },
	Key { label: "F10", scan_code: 0x44 },
	Key { label: "F11", scan_code: 0x57 },
	Key { label: "F12", scan_code: 0x58 },
	Key { label: "PrintScreen", scan_code: 0xE0A2 },
	Key { label: "Ctl+PrtScrn", scan_code: 0xE037 },
	Key { label: "Shft+PrtScrn", scan_code: 0xE037 },
	Key { label: "Alt+PrtScrn", scan_code: 0x54 },
	Key { label: "Scroll Lock", scan_code: 0x46 },
	Key { label: "L-Win", scan_code: 0xE05B },
	Key { label: "R-Win", scan_code: 0xE05C },
	Key { label: "Apps", scan_code: 0xE05D },
	Key { label: "Browser back", scan_code: 0xE06A },
	Key { label: "Browser forward", scan_code: 0xE069 },
	Key { label: "Browser refresh", scan_code: 0xE067 },
	Key { label: "Browser stop", scan_code: 0xE068 },
	Key { label: "Browser search", scan_code: 0xE065 },
	Key { label: "Browser favorites", scan_code: 0xE066 },
	Key { label: "Browser home", scan_code: 0xE032 },
];
