pub struct Key {
	pub label: String,
	pub scan_code: u32,
}

impl Key {
	pub fn print_scan_code(&self) -> String {
		format!("{:02x},{:02x}", self.scan_code & 0xff, self.scan_code & 0xff00)
	}
}

pub fn get_keys<'a>() -> Vec<Key> {
	vec![
		Key { label: "~ `".to_string(), scan_code: 0x29 },
		Key { label: "! 1".to_string(), scan_code: 0x02 },
		Key { label: "@ 2".to_string(), scan_code: 0x03 },
		Key { label: "# 3".to_string(), scan_code: 0x04 },
		Key { label: "$ 4".to_string(), scan_code: 0x05 },
		Key { label: "% 5".to_string(), scan_code: 0x06 },
		Key { label: "^ 6".to_string(), scan_code: 0x07 },
		Key { label: "& 7".to_string(), scan_code: 0x08 },
		Key { label: "* 8".to_string(), scan_code: 0x09 },
		Key { label: "( 9".to_string(), scan_code: 0x0A },
		Key { label: ") 0".to_string(), scan_code: 0x0B },
		Key { label: "_ -".to_string(), scan_code: 0x0C },
		Key { label: "+ =".to_string(), scan_code: 0x0D },
		Key { label: "Backspace".to_string(), scan_code: 0x0E },
		Key { label: "Tab".to_string(), scan_code: 0x0F },
		Key { label: "Q".to_string(), scan_code: 0x10 },
		Key { label: "W".to_string(), scan_code: 0x11 },
		Key { label: "E".to_string(), scan_code: 0x12 },
		Key { label: "R".to_string(), scan_code: 0x13 },
		Key { label: "T".to_string(), scan_code: 0x14 },
		Key { label: "Y".to_string(), scan_code: 0x15 },
		Key { label: "U".to_string(), scan_code: 0x16 },
		Key { label: "I".to_string(), scan_code: 0x17 },
		Key { label: "O".to_string(), scan_code: 0x18 },
		Key { label: "P".to_string(), scan_code: 0x19 },
		Key { label: "{ [".to_string(), scan_code: 0x1A },
		Key { label: "} ]".to_string(), scan_code: 0x1B },
		Key { label: "| \\".to_string(), scan_code: 0x2B },
		Key { label: "Caps Lock".to_string(), scan_code: 0x3A },
		Key { label: "A".to_string(), scan_code: 0x1E },
		Key { label: "S".to_string(), scan_code: 0x1F },
		Key { label: "D".to_string(), scan_code: 0x20 },
		Key { label: "F".to_string(), scan_code: 0x21 },
		Key { label: "G".to_string(), scan_code: 0x22 },
		Key { label: "H".to_string(), scan_code: 0x23 },
		Key { label: "J".to_string(), scan_code: 0x24 },
		Key { label: "K".to_string(), scan_code: 0x25 },
		Key { label: "L".to_string(), scan_code: 0x26 },
		Key { label: ": ;".to_string(), scan_code: 0x27 },
		Key { label: "\" '".to_string(), scan_code: 0x28 },
		Key { label: "(in'tl )".to_string(), scan_code: 0x2B },
		Key { label: "Enter".to_string(), scan_code: 0x1C },
		Key { label: "L SHIFT".to_string(), scan_code: 0x2A },
		Key { label: "(in'tl )".to_string(), scan_code: 0x56 },
		Key { label: "Z".to_string(), scan_code: 0x2C },
		Key { label: "X".to_string(), scan_code: 0x2D },
		Key { label: "C".to_string(), scan_code: 0x2E },
		Key { label: "V".to_string(), scan_code: 0x2F },
		Key { label: "B".to_string(), scan_code: 0x30 },
		Key { label: "N".to_string(), scan_code: 0x31 },
		Key { label: "M".to_string(), scan_code: 0x32 },
		Key { label: "< ,".to_string(), scan_code: 0x33 },
		Key { label: "> .".to_string(), scan_code: 0x34 },
		Key { label: "? /".to_string(), scan_code: 0x35 },
		Key { label: "(in'tl )".to_string(), scan_code: 0x73 },
		Key { label: "R SHIFT".to_string(), scan_code: 0x36 },
		Key { label: "L CTRL".to_string(), scan_code: 0x1D },
		Key { label: "L ALT".to_string(), scan_code: 0x38 },
		Key { label: "Space Bar".to_string(), scan_code: 0x39 },
		Key { label: "R ALT".to_string(), scan_code: 0xE038 },
		Key { label: "R CTRL".to_string(), scan_code: 0xE01D },
		Key { label: "Insert".to_string(), scan_code: 0xE052 },
		Key { label: "Delete".to_string(), scan_code: 0xE053 },
		Key { label: "L Arrow".to_string(), scan_code: 0xE04B },
		Key { label: "Home".to_string(), scan_code: 0xE047 },
		Key { label: "End".to_string(), scan_code: 0xE04F },
		Key { label: "Up Arrow".to_string(), scan_code: 0xE048 },
		Key { label: "Dn Arrow".to_string(), scan_code: 0xE050 },
		Key { label: "Page Up".to_string(), scan_code: 0xE049 },
		Key { label: "Page Down".to_string(), scan_code: 0xE051 },
		Key { label: "R Arrow".to_string(), scan_code: 0xE04D },
		Key { label: "Num Lock".to_string(), scan_code: 0x45 },
		Key { label: "Num 7".to_string(), scan_code: 0x47 },
		Key { label: "Num 4".to_string(), scan_code: 0x4B },
		Key { label: "Num 1".to_string(), scan_code: 0x4F },
		Key { label: "Num /".to_string(), scan_code: 0xE035 },
		Key { label: "LS+Num /".to_string(), scan_code: 0xE0B5 },
		Key { label: "RS+Num /".to_string(), scan_code: 0xE0B6 },
		Key { label: "Num 8".to_string(), scan_code: 0x48 },
		Key { label: "Num 5".to_string(), scan_code: 0x4C },
		Key { label: "Num 2".to_string(), scan_code: 0x50 },
		Key { label: "Num 0".to_string(), scan_code: 0x52 },
		Key { label: "Num *".to_string(), scan_code: 0x37 },
		Key { label: "Num 9".to_string(), scan_code: 0x49 },
		Key { label: "Num 6".to_string(), scan_code: 0x4D },
		Key { label: "Num 3".to_string(), scan_code: 0x51 },
		Key { label: "Num .".to_string(), scan_code: 0x53 },
		Key { label: "Num -".to_string(), scan_code: 0x4A },
		Key { label: "Num +".to_string(), scan_code: 0x4E },
		Key { label: "(in'tl )".to_string(), scan_code: 0x7E },
		Key { label: "NumEnter".to_string(), scan_code: 0xE01C },
		Key { label: "Esc".to_string(), scan_code: 0x01 },
		Key { label: "F1".to_string(), scan_code: 0x3B },
		Key { label: "F2".to_string(), scan_code: 0x3C },
		Key { label: "F3".to_string(), scan_code: 0x3D },
		Key { label: "F4".to_string(), scan_code: 0x3E },
		Key { label: "F5".to_string(), scan_code: 0x3F },
		Key { label: "F6".to_string(), scan_code: 0x40 },
		Key { label: "F7".to_string(), scan_code: 0x41 },
		Key { label: "F8".to_string(), scan_code: 0x42 },
		Key { label: "F9".to_string(), scan_code: 0x43 },
		Key { label: "F10".to_string(), scan_code: 0x44 },
		Key { label: "F11".to_string(), scan_code: 0x57 },
		Key { label: "F12".to_string(), scan_code: 0x58 },
		Key { label: "PrintScreen".to_string(), scan_code: 0xE0A2 },
		Key { label: "Ctl+PrtScrn".to_string(), scan_code: 0xE037 },
		Key { label: "Shft+PrtScrn".to_string(), scan_code: 0xE037 },
		Key { label: "Alt+PrtScrn".to_string(), scan_code: 0x54 },
		Key { label: "Scroll Lock".to_string(), scan_code: 0x46 },
		Key { label: "L-Win".to_string(), scan_code: 0xE05B },
		Key { label: "R-Win".to_string(), scan_code: 0xE05C },
		Key { label: "Apps".to_string(), scan_code: 0xE05D },
		Key { label: "Browser back".to_string(), scan_code: 0xE06A},
		Key { label: "Browser forward".to_string(), scan_code: 0xE069},
		Key { label: "Browser refresh".to_string(), scan_code: 0xE067},
		Key { label: "Browser stop".to_string(), scan_code: 0xE068},
		Key { label: "Browser search".to_string(), scan_code: 0xE065},
		Key { label: "Browser favorites".to_string(), scan_code: 0xE066},
		Key { label: "Browser home".to_string(), scan_code: 0xE032},
	]
}
